version: '3.8'

services:
  app:
    build: .
    container_name: rrhh_app
    ports:
      - "80:80"
    env_file:
      - .env.production
    extra_hosts:
      - "host-gateway:host-gateway"
    restart: always
